on:
  push:

jobs:

  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy Docs and other things
        run: |
          mkdir -p www
          cp -r prisma/docs www/docs
          cp prisma/ERD.pdf www/ERD.pdf
          cp prisma/ERD.svg www/ERD.svg
          cp README.md www/index.md
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './www'

  deploy:
    runs-on: ubuntu-latest
    needs: fetch
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  
      